spring:
  profiles:
#  当前运行加载配置文件：dev：application-dev.yml,可根据实际情况配置
    active: dev

logging:
  #配置日志文件路径
  path: e:\log
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error